platform :ios, '10.0'
use_frameworks!
def appodeal
    pod 'APDAdColonyAdapter', '2.11.1.3'
    pod 'APDAmazonAdsAdapter', '2.11.1.2'
    pod 'APDAppLovinAdapter', '2.11.1.3'
    pod 'APDBidMachineAdapter', '2.11.1.3' # Required
    pod 'APDFacebookAudienceAdapter', '2.11.1.2'
    pod 'APDGoogleAdMobAdapter', '2.11.1.3'
    pod 'APDIronSourceAdapter', '2.11.1.3'
    pod 'APDMyTargetAdapter', '2.11.1.2'
    pod 'APDOguryAdapter', '2.11.1.1'
    pod 'APDUnityAdapter', '2.11.1.2'
    pod 'APDVungleAdapter', '2.11.1.2'
    pod 'APDYandexAdapter', '2.11.1.1'
end

target 'iOSPods' do
    appodeal
    pod 'Google-Mobile-Ads-SDK'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleAppMeasurement'
    pod 'FBAudienceNetwork'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
