platform :ios, '10.0'
use_frameworks!
def appodeal
    pod 'APDAdColonyAdapter', '2.10.1.1'
    pod 'APDAmazonAdsAdapter', '2.10.1.1'
    pod 'APDAppLovinAdapter', '2.10.1.2'
    pod 'APDBidMachineAdapter', '2.10.1.3' # Required
    pod 'APDChartboostAdapter', '2.10.1.1'
    pod 'APDFacebookAudienceAdapter', '2.10.1.2'
    pod 'APDGoogleAdMobAdapter', '2.10.1.1'
    pod 'APDInMobiAdapter', '2.10.1.1'
    pod 'APDIronSourceAdapter', '2.10.1.2'
    pod 'APDMintegralAdapter', '2.10.1.1'
    pod 'APDMyTargetAdapter', '2.10.1.2'
    pod 'APDOguryAdapter', '2.10.1.1'
    pod 'APDSmaatoAdapter', '2.10.1.1'
    pod 'APDStartAppAdapter', '2.10.1.2'
    pod 'APDTapjoyAdapter', '2.10.1.1'
    pod 'APDTwitterMoPubAdapter', '2.10.1.1'
    pod 'APDUnityAdapter', '2.10.1.1'
    pod 'APDVungleAdapter', '2.10.1.1'
    pod 'APDYandexAdapter', '2.10.1.1'
end

target 'iOSPods' do
    appodeal
    pod 'Google-Mobile-Ads-SDK'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleAppMeasurement'
    pod 'FBAudienceNetwork'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
