platform :ios, '10.0'

use_frameworks!

def appodeal
    pod 'APDAdColonyAdapter', '2.8.1.1' 
    pod 'APDAmazonAdsAdapter', '2.8.1.1' 
    pod 'APDAppLovinAdapter', '2.8.1.1' 
    # pod 'APDBidMachineAdapter', '2.8.1.1' 
    pod 'APDFacebookAudienceAdapter', '2.8.1.1' 
    pod 'APDGoogleAdMobAdapter', '2.8.1.1' 
    pod 'APDIronSourceAdapter', '2.8.1.1' 
    pod 'APDMyTargetAdapter', '2.8.1.1' 
    pod 'APDOguryAdapter', '2.8.1.1' 
    pod 'APDSmaatoAdapter', '2.8.1.1' 
    pod 'APDStartAppAdapter', '2.8.1.1' 
    pod 'APDUnityAdapter', '2.8.1.1' 
    pod 'APDVungleAdapter', '2.8.1.1' 
    pod 'APDYandexAdapter', '2.8.1.1' 
end


target 'iOSPods' do
    appodeal
    pod 'Google-Mobile-Ads-SDK'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleAppMeasurement'

    pod 'FBAudienceNetwork'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
end
