// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/analytics/analyctis.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ADCOMAd;
@class ADCOMContext;
@class ADCOMPlacement;
@class AuctionContext;
@class ORTBRequest_Item;
@class ORTBResponse_Seatbid_Bid;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PlacementTag

typedef GPB_ENUM(PlacementTag) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PlacementTag_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PlacementTag_PlacementTagInvalid = 0,
  PlacementTag_PlacementTagDisplayBanner = 1,
  PlacementTag_PlacementTagDisplayInterstitial = 2,
  PlacementTag_PlacementTagDisplayNative = 3,
  PlacementTag_PlacementTagVideo = 4,
  PlacementTag_PlacementTagRewardedVideo = 5,
};

GPBEnumDescriptor *PlacementTag_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PlacementTag_IsValidValue(int32_t value);

#pragma mark - AnalyctisRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AnalyctisRoot : GPBRootObject
@end

#pragma mark - AuctionContext

typedef GPB_ENUM(AuctionContext_FieldNumber) {
  AuctionContext_FieldNumber_Timestamp = 1,
  AuctionContext_FieldNumber_Id_p = 2,
  AuctionContext_FieldNumber_Test = 3,
  AuctionContext_FieldNumber_At = 4,
  AuctionContext_FieldNumber_PlacementTag = 5,
  AuctionContext_FieldNumber_Item = 6,
  AuctionContext_FieldNumber_Placement = 7,
  AuctionContext_FieldNumber_Context = 8,
};

GPB_FINAL @interface AuctionContext : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite) BOOL test;

@property(nonatomic, readwrite) uint32_t at;

@property(nonatomic, readwrite) PlacementTag placementTag;

@property(nonatomic, readwrite, strong, null_resettable) ORTBRequest_Item *item;
/** Test to see if @c item has been set. */
@property(nonatomic, readwrite) BOOL hasItem;

@property(nonatomic, readwrite, strong, null_resettable) ADCOMPlacement *placement;
/** Test to see if @c placement has been set. */
@property(nonatomic, readwrite) BOOL hasPlacement;

@property(nonatomic, readwrite, strong, null_resettable) ADCOMContext *context;
/** Test to see if @c context has been set. */
@property(nonatomic, readwrite) BOOL hasContext;

@end

/**
 * Fetches the raw value of a @c AuctionContext's @c placementTag property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AuctionContext_PlacementTag_RawValue(AuctionContext *message);
/**
 * Sets the raw value of an @c AuctionContext's @c placementTag property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAuctionContext_PlacementTag_RawValue(AuctionContext *message, int32_t value);

#pragma mark - BidEvent

typedef GPB_ENUM(BidEvent_FieldNumber) {
  BidEvent_FieldNumber_Timestamp = 1,
  BidEvent_FieldNumber_Bidid = 2,
  BidEvent_FieldNumber_Seat = 3,
  BidEvent_FieldNumber_AuctionContext = 4,
  BidEvent_FieldNumber_Bid = 5,
  BidEvent_FieldNumber_Ad = 6,
};

GPB_FINAL @interface BidEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bidid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *seat;

@property(nonatomic, readwrite, strong, null_resettable) AuctionContext *auctionContext;
/** Test to see if @c auctionContext has been set. */
@property(nonatomic, readwrite) BOOL hasAuctionContext;

@property(nonatomic, readwrite, strong, null_resettable) ORTBResponse_Seatbid_Bid *bid;
/** Test to see if @c bid has been set. */
@property(nonatomic, readwrite) BOOL hasBid;

@property(nonatomic, readwrite, strong, null_resettable) ADCOMAd *ad;
/** Test to see if @c ad has been set. */
@property(nonatomic, readwrite) BOOL hasAd;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
