// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class APDAdStats;
@class APDAdapter;
@class APDApp;
@class APDDevice;
@class APDEvent;
@class APDExtra;
@class APDGeo;
@class APDGet;
@class APDRegs;
@class APDServices;
@class APDServices_Adjust;
@class APDServices_Appsflyer;
@class APDServices_Facebook;
@class APDServices_Firebase;
@class APDSession;
@class APDStats;
@class APDStats_AdUnit;
@class APDUser;
@class APDUserSettings;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum APDDevice_ConnectionType

typedef GPB_ENUM(APDDevice_ConnectionType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDDevice_ConnectionType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDDevice_ConnectionType_ConnectiontypeUnknown = 0,
  APDDevice_ConnectionType_Ethernet = 1,
  APDDevice_ConnectionType_Wifi = 2,
  APDDevice_ConnectionType_MobileUnknown = 3,
  APDDevice_ConnectionType_Mobile2G = 4,
  APDDevice_ConnectionType_Mobile3G = 5,
  APDDevice_ConnectionType_Mobile4G = 6,
};

GPBEnumDescriptor *APDDevice_ConnectionType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDDevice_ConnectionType_IsValidValue(int32_t value);

#pragma mark - Enum APDDevice_DeviceType

typedef GPB_ENUM(APDDevice_DeviceType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDDevice_DeviceType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDDevice_DeviceType_DevicetypeUnknown = 0,
  APDDevice_DeviceType_Phone = 4,
  APDDevice_DeviceType_Tablet = 5,
};

GPBEnumDescriptor *APDDevice_DeviceType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDDevice_DeviceType_IsValidValue(int32_t value);

#pragma mark - Enum APDDevice_TrackingAuthorizationStatus

typedef GPB_ENUM(APDDevice_TrackingAuthorizationStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDDevice_TrackingAuthorizationStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDDevice_TrackingAuthorizationStatus_NotDetermined = 0,
  APDDevice_TrackingAuthorizationStatus_Restricted = 1,
  APDDevice_TrackingAuthorizationStatus_Denied = 2,
  APDDevice_TrackingAuthorizationStatus_Authorized = 3,
};

GPBEnumDescriptor *APDDevice_TrackingAuthorizationStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDDevice_TrackingAuthorizationStatus_IsValidValue(int32_t value);

#pragma mark - Enum APDGeo_LocationType

typedef GPB_ENUM(APDGeo_LocationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDGeo_LocationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDGeo_LocationType_LocationtypeUnknown = 0,
  APDGeo_LocationType_Gps = 1,
  APDGeo_LocationType_Ip = 2,
  APDGeo_LocationType_Userprovided = 3,
};

GPBEnumDescriptor *APDGeo_LocationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDGeo_LocationType_IsValidValue(int32_t value);

#pragma mark - Enum APDStats_AdUnitRequestResult

typedef GPB_ENUM(APDStats_AdUnitRequestResult) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDStats_AdUnitRequestResult_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDStats_AdUnitRequestResult_Successful = 0,
  APDStats_AdUnitRequestResult_Nofill = 1,
  APDStats_AdUnitRequestResult_Timeoutreached = 2,
  APDStats_AdUnitRequestResult_Exception = 3,
  APDStats_AdUnitRequestResult_Undefinedadapter = 4,
  APDStats_AdUnitRequestResult_Incorrectadunit = 5,
  APDStats_AdUnitRequestResult_Invalidassets = 6,
  APDStats_AdUnitRequestResult_Canceled = 7,
};

GPBEnumDescriptor *APDStats_AdUnitRequestResult_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDStats_AdUnitRequestResult_IsValidValue(int32_t value);

#pragma mark - Enum APDEvent_EventType

typedef GPB_ENUM(APDEvent_EventType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  APDEvent_EventType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  APDEvent_EventType_Install = 0,
  APDEvent_EventType_Iap = 1,
  APDEvent_EventType_Show = 2,
  APDEvent_EventType_Click = 3,
  APDEvent_EventType_Finish = 4,
};

GPBEnumDescriptor *APDEvent_EventType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL APDEvent_EventType_IsValidValue(int32_t value);

#pragma mark - APDApiRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface APDApiRoot : GPBRootObject
@end

#pragma mark - APDApp

typedef GPB_ENUM(APDApp_FieldNumber) {
  APDApp_FieldNumber_Bundle = 1,
  APDApp_FieldNumber_Ver = 2,
  APDApp_FieldNumber_InstallTime = 3,
  APDApp_FieldNumber_PluginVersion = 4,
  APDApp_FieldNumber_Installer = 5,
  APDApp_FieldNumber_Multidex = 6,
  APDApp_FieldNumber_AppKey = 7,
  APDApp_FieldNumber_Sdk = 8,
  APDApp_FieldNumber_VersionCode = 9,
  APDApp_FieldNumber_AppUptime = 10,
  APDApp_FieldNumber_Framework = 11,
  APDApp_FieldNumber_FrameworkVersion = 12,
  APDApp_FieldNumber_MonotonicAppUptime = 13,
  APDApp_FieldNumber_ActiveAppUptime = 14,
};

/**
 * Application data
 **/
GPB_FINAL @interface APDApp : GPBMessage

/** Application bundle *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundle;

/** Application version *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ver;

/** Application instalation timestamp in seconds *Required* */
@property(nonatomic, readwrite) int64_t installTime;

/** Plugin version *Required if using a plugin* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *pluginVersion;

/** Application installer */
@property(nonatomic, readwrite, copy, null_resettable) NSString *installer;

/** Is multidex enable in application (android specific) */
@property(nonatomic, readwrite) BOOL multidex GPB_DEPRECATED_MSG("com.appodeal.ads.App.multidex is deprecated (see api.proto).");

/** Appodeal application key *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appKey;

/** Appodeal SDK version *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdk;

/** versionCode from build settings (android specific) */
@property(nonatomic, readwrite) int32_t versionCode;

/** Sum of all application sessions up time *Required* */
@property(nonatomic, readwrite) int64_t appUptime;

/** Name of framework *Required if using a framework* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *framework;

/** Version of framework *Required if using a framework* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *frameworkVersion;

/** Sum of all application session monotonic up time *Required* */
@property(nonatomic, readwrite) int64_t monotonicAppUptime;

/** Sum of all application session active time *Required* */
@property(nonatomic, readwrite) int64_t activeAppUptime GPB_DEPRECATED_MSG("com.appodeal.ads.App.active_app_uptime is deprecated (see api.proto).");

@end

#pragma mark - APDDevice

typedef GPB_ENUM(APDDevice_FieldNumber) {
  APDDevice_FieldNumber_Ua = 1,
  APDDevice_FieldNumber_Osv = 2,
  APDDevice_FieldNumber_Os = 3,
  APDDevice_FieldNumber_W = 4,
  APDDevice_FieldNumber_H = 5,
  APDDevice_FieldNumber_Pxratio = 6,
  APDDevice_FieldNumber_Devicetype = 7,
  APDDevice_FieldNumber_Make = 8,
  APDDevice_FieldNumber_Model = 9,
  APDDevice_FieldNumber_Rooted = 10,
  APDDevice_FieldNumber_WebviewVersion = 11,
  APDDevice_FieldNumber_Battery = 12,
  APDDevice_FieldNumber_Mccmnc = 13,
  APDDevice_FieldNumber_Locale = 14,
  APDDevice_FieldNumber_Connectiontype = 15,
  APDDevice_FieldNumber_Ifa = 16,
  APDDevice_FieldNumber_Lmt = 17,
  APDDevice_FieldNumber_Adidg = 18,
  APDDevice_FieldNumber_TrackingStatus = 19,
  APDDevice_FieldNumber_Idfv = 20,
  APDDevice_FieldNumber_StorageSize = 21,
  APDDevice_FieldNumber_StorageFree = 22,
  APDDevice_FieldNumber_StorageUsed = 23,
  APDDevice_FieldNumber_RamSize = 24,
  APDDevice_FieldNumber_RamFree = 25,
  APDDevice_FieldNumber_RamUsed = 26,
  APDDevice_FieldNumber_CpuUsage = 27,
  APDDevice_FieldNumber_SecureAndroidId = 28,
};

/**
 * Device data
 **/
GPB_FINAL @interface APDDevice : GPBMessage

/** Browser user agent string. (was user_agent) *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ua;

/** OS version (was android) *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osv;

/** Application platform *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *os;

/** Physical width of the screen in pixels *Required* */
@property(nonatomic, readwrite) int32_t w;

/** Physical height of the screen in pixels *Required* */
@property(nonatomic, readwrite) int32_t h;

/** The ratio of physical pixels to device independent pixels *Required* */
@property(nonatomic, readwrite) float pxratio;

/** Device type (was device_type) *Required* */
@property(nonatomic, readwrite) APDDevice_DeviceType devicetype;

/** Device make (was manufacturer) *Required* ~Coppa restricted~ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *make;

/** Device model *Required* ~Coppa restricted~ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** Device root status */
@property(nonatomic, readwrite) BOOL rooted GPB_DEPRECATED_MSG("com.appodeal.ads.Device.rooted is deprecated (see api.proto).");

/** WebView version (android specific) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *webviewVersion GPB_DEPRECATED_MSG("com.appodeal.ads.Device.webview_version is deprecated (see api.proto).");

/** Battery level */
@property(nonatomic, readwrite) int32_t battery;

/** Mobile carrier as the concatenated MCC-MNC code (was crr) ~Coppa restricted~ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mccmnc;

/** Device locale (e.g. language_region) *Required* ~Coppa restricted~ */
@property(nonatomic, readwrite, copy, null_resettable) NSString *locale;

/** Network connection type (was connection) *Required* ~Coppa restricted~ */
@property(nonatomic, readwrite) APDDevice_ConnectionType connectiontype;

/** ID sanctioned for advertiser use in the clear (was android_id) *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ifa;

/** Limit Ad Tracking signal commercially endorsed (e.g., iOS, Android), where 0 = tracking is unrestricted, 1 = tracking mustbe limited per commercial guidelines. (was advertising_tracking) *Required* */
@property(nonatomic, readwrite) int32_t lmt;

/** Is ID sanctioned for advertiser was generated on device *Required if true* */
@property(nonatomic, readwrite) BOOL adidg;

/** AppTrackingTransparency status for iOS higher than or equal to 14 version */
@property(nonatomic, readwrite) APDDevice_TrackingAuthorizationStatus trackingStatus;

/** An alphanumeric string that uniquely identifies a device to the app’s vendor. *Required* only for iOS platform. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *idfv;

/** Disk size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t storageSize;

/** Available disk size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t storageFree;

/** Used disk size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t storageUsed;

/** RAM size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t ramSize;

/** Available RAM size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t ramFree;

/** Used RAM size in bytes. *Required* */
@property(nonatomic, readwrite) uint64_t ramUsed;

/** Summary CPU load. Value in range from 0 to 1. *Required* */
@property(nonatomic, readwrite) float cpuUsage;

/** Android specific id, 64-bit number (expressed as a hexadecimal string), unique to each combination of app-signing key, user, and device. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *secureAndroidId;

@end

/**
 * Fetches the raw value of a @c APDDevice's @c devicetype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDDevice_Devicetype_RawValue(APDDevice *message);
/**
 * Sets the raw value of an @c APDDevice's @c devicetype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDDevice_Devicetype_RawValue(APDDevice *message, int32_t value);

/**
 * Fetches the raw value of a @c APDDevice's @c connectiontype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDDevice_Connectiontype_RawValue(APDDevice *message);
/**
 * Sets the raw value of an @c APDDevice's @c connectiontype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDDevice_Connectiontype_RawValue(APDDevice *message, int32_t value);

/**
 * Fetches the raw value of a @c APDDevice's @c trackingStatus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDDevice_TrackingStatus_RawValue(APDDevice *message);
/**
 * Sets the raw value of an @c APDDevice's @c trackingStatus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDDevice_TrackingStatus_RawValue(APDDevice *message, int32_t value);

#pragma mark - APDGeo

typedef GPB_ENUM(APDGeo_FieldNumber) {
  APDGeo_FieldNumber_Utcoffset = 1,
  APDGeo_FieldNumber_LocalTime = 2,
  APDGeo_FieldNumber_Lt = 3,
  APDGeo_FieldNumber_Lat = 4,
  APDGeo_FieldNumber_Lon = 5,
};

/**
 * Geo data
 **/
GPB_FINAL @interface APDGeo : GPBMessage

/** Local time as the number +/- of minutes from UTC (was timezone) *Required* */
@property(nonatomic, readwrite) int32_t utcoffset;

/** Device timestamp in seconds *Required* */
@property(nonatomic, readwrite) int64_t localTime;

/** Source of location data ~Coppa restricted~ */
@property(nonatomic, readwrite) APDGeo_LocationType lt;

/** Latitude from -90.0 to +90.0, where negative is south ~Coppa restricted~ */
@property(nonatomic, readwrite) float lat;

/** Longitude from -180.0 to +180.0, where negative is west ~Coppa restricted~ */
@property(nonatomic, readwrite) float lon;

@end

/**
 * Fetches the raw value of a @c APDGeo's @c lt property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDGeo_Lt_RawValue(APDGeo *message);
/**
 * Sets the raw value of an @c APDGeo's @c lt property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDGeo_Lt_RawValue(APDGeo *message, int32_t value);

#pragma mark - APDRegs

typedef GPB_ENUM(APDRegs_FieldNumber) {
  APDRegs_FieldNumber_Coppa = 1,
};

/**
 * Regulations data
 **/
GPB_FINAL @interface APDRegs : GPBMessage

/** Flag indicating if this request is subject to the COPPA regulations established by the USA FTC, where 0 = no, 1 = yes *Required if true* */
@property(nonatomic, readwrite) BOOL coppa;

@end

#pragma mark - APDUser

typedef GPB_ENUM(APDUser_FieldNumber) {
  APDUser_FieldNumber_Consent = 1,
  APDUser_FieldNumber_UserSettings = 2,
  APDUser_FieldNumber_Id_p = 3,
  APDUser_FieldNumber_IabConsentData = 4,
};

/**
 * User data
 **/
GPB_FINAL @interface APDUser : GPBMessage

/** Is consent was obtained from user *Required* */
@property(nonatomic, readwrite) BOOL consent;

/** ~Coppa restricted~ */
@property(nonatomic, readwrite, strong, null_resettable) APDUserSettings *userSettings;
/** Test to see if @c userSettings has been set. */
@property(nonatomic, readwrite) BOOL hasUserSettings;

/** Publisher-specific user ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** iAB Object JSON serialized string from Consent Manager result *Optional* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *iabConsentData;

@end

#pragma mark - APDUserSettings

typedef GPB_ENUM(APDUserSettings_FieldNumber) {
  APDUserSettings_FieldNumber_UserId = 1,
  APDUserSettings_FieldNumber_Gender = 2,
  APDUserSettings_FieldNumber_Age = 3,
};

/**
 * User settings
 **/
GPB_FINAL @interface APDUserSettings : GPBMessage

/** Publisher-specific user ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId GPB_DEPRECATED_MSG("com.appodeal.ads.UserSettings.user_id is deprecated (see api.proto).");

/** Gender, where “M” = male, “F” = female, “O” = known to be other (i.e., omitted is unknown) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gender GPB_DEPRECATED_MSG("com.appodeal.ads.UserSettings.gender is deprecated (see api.proto).");

/** User age */
@property(nonatomic, readwrite) int32_t age GPB_DEPRECATED_MSG("com.appodeal.ads.UserSettings.age is deprecated (see api.proto).");

@end

#pragma mark - APDSession

typedef GPB_ENUM(APDSession_FieldNumber) {
  APDSession_FieldNumber_Test = 1,
  APDSession_FieldNumber_Ext = 2,
  APDSession_FieldNumber_Token = 3,
  APDSession_FieldNumber_SessionId = 4,
  APDSession_FieldNumber_SessionUuid = 5,
  APDSession_FieldNumber_SessionUptime = 6,
  APDSession_FieldNumber_SegmentId = 7,
  APDSession_FieldNumber_AdStats = 8,
  APDSession_FieldNumber_MonotonicSessionUptime = 9,
  APDSession_FieldNumber_ActiveSessionUptime = 10,
  APDSession_FieldNumber_ActiveSessionId = 11,
  APDSession_FieldNumber_AppSessionAverageLength = 12,
  APDSession_FieldNumber_MonotonicAppSessionAverageLength = 13,
};

/**
 * Session data
 **/
GPB_FINAL @interface APDSession : GPBMessage

/** Is app works in test mode *Required if true* */
@property(nonatomic, readwrite) BOOL test;

/** Extra data passed from the app (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ext;

/** Token which was received from server (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** Application session count *Required* */
@property(nonatomic, readwrite) int64_t sessionId;

/** Session uuid generated on device *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionUuid;

/** Application session up time *Required* */
@property(nonatomic, readwrite) int64_t sessionUptime;

/** Segment id which was matched *Required everywhere except Get request* */
@property(nonatomic, readwrite) int32_t segmentId;

/** Advertising statistics in current session */
@property(nonatomic, readwrite, strong, null_resettable) APDAdStats *adStats;
/** Test to see if @c adStats has been set. */
@property(nonatomic, readwrite) BOOL hasAdStats;

/** Application monotonic session up time *Required* */
@property(nonatomic, readwrite) int64_t monotonicSessionUptime;

/** Application session active time *Required* */
@property(nonatomic, readwrite) int64_t activeSessionUptime GPB_DEPRECATED_MSG("com.appodeal.ads.Session.active_session_uptime is deprecated (see api.proto).");

/** ID of the active session, initialization counter *Required* */
@property(nonatomic, readwrite) int32_t activeSessionId GPB_DEPRECATED_MSG("com.appodeal.ads.Session.active_session_id is deprecated (see api.proto).");

/** Average session time calculated on SDK side *Required* */
@property(nonatomic, readwrite) int64_t appSessionAverageLength;

/** Average monotonic session time calculated on SDK side *Required* */
@property(nonatomic, readwrite) int64_t monotonicAppSessionAverageLength;

@end

#pragma mark - APDExtra

typedef GPB_ENUM(APDExtra_FieldNumber) {
  APDExtra_FieldNumber_PriceFloor = 1,
  APDExtra_FieldNumber_AdUnitStat = 2,
  APDExtra_FieldNumber_AppsArray = 3,
  APDExtra_FieldNumber_SaArray = 4,
};

/**
 * Extra data
 **/
GPB_FINAL @interface APDExtra : GPBMessage

/** Price floor setting from the matched segment */
@property(nonatomic, readwrite) float priceFloor;

/** Extra ad unit statistics (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *adUnitStat;

/** Installed apps */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *appsArray GPB_DEPRECATED_MSG("com.appodeal.ads.Extra.apps is deprecated (see api.proto).");
/** The number of items in @c appsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger appsArray_Count GPB_DEPRECATED_MSG("com.appodeal.ads.Extra.apps is deprecated (see api.proto).");

/** Suspicious activities */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *saArray;
/** The number of items in @c saArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger saArray_Count;

@end

#pragma mark - APDAdStats

typedef GPB_ENUM(APDAdStats_FieldNumber) {
  APDAdStats_FieldNumber_Show = 1,
  APDAdStats_FieldNumber_Click = 2,
  APDAdStats_FieldNumber_Finish = 3,
  APDAdStats_FieldNumber_BannerShow = 4,
  APDAdStats_FieldNumber_BannerClick = 5,
  APDAdStats_FieldNumber_VideoShow = 6,
  APDAdStats_FieldNumber_VideoClick = 7,
  APDAdStats_FieldNumber_VideoFinish = 8,
  APDAdStats_FieldNumber_RewardedVideoShow = 9,
  APDAdStats_FieldNumber_RewardedVideoClick = 10,
  APDAdStats_FieldNumber_RewardedVideoFinish = 11,
  APDAdStats_FieldNumber_Banner320Show = 12,
  APDAdStats_FieldNumber_Banner320Click = 13,
  APDAdStats_FieldNumber_BannerMrecShow = 14,
  APDAdStats_FieldNumber_BannerMrecClick = 15,
  APDAdStats_FieldNumber_NativeShow = 16,
  APDAdStats_FieldNumber_NativeClick = 17,
};

/**
 * Ad statistics data
 **/
GPB_FINAL @interface APDAdStats : GPBMessage

@property(nonatomic, readwrite) int32_t show;

@property(nonatomic, readwrite) int32_t click;

@property(nonatomic, readwrite) int32_t finish;

@property(nonatomic, readwrite) int32_t bannerShow;

@property(nonatomic, readwrite) int32_t bannerClick;

@property(nonatomic, readwrite) int32_t videoShow;

@property(nonatomic, readwrite) int32_t videoClick;

@property(nonatomic, readwrite) int32_t videoFinish;

@property(nonatomic, readwrite) int32_t rewardedVideoShow;

@property(nonatomic, readwrite) int32_t rewardedVideoClick;

@property(nonatomic, readwrite) int32_t rewardedVideoFinish;

@property(nonatomic, readwrite) int32_t banner320Show;

@property(nonatomic, readwrite) int32_t banner320Click;

@property(nonatomic, readwrite) int32_t bannerMrecShow;

@property(nonatomic, readwrite) int32_t bannerMrecClick;

@property(nonatomic, readwrite) int32_t nativeShow;

@property(nonatomic, readwrite) int32_t nativeClick;

@end

#pragma mark - APDAdapter

typedef GPB_ENUM(APDAdapter_FieldNumber) {
  APDAdapter_FieldNumber_Status = 1,
  APDAdapter_FieldNumber_Version = 2,
  APDAdapter_FieldNumber_NetworkSdkVersion = 3,
};

GPB_FINAL @interface APDAdapter : GPBMessage

/** Adapter network name registered in Appodeal *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

/** Adapter version *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** Ad Network SDK version used by adapter *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *networkSdkVersion;

@end

#pragma mark - APDRequest

typedef GPB_ENUM(APDRequest_FieldNumber) {
  APDRequest_FieldNumber_App = 1,
  APDRequest_FieldNumber_Session = 2,
  APDRequest_FieldNumber_Device = 3,
  APDRequest_FieldNumber_User = 4,
  APDRequest_FieldNumber_Regs = 5,
  APDRequest_FieldNumber_Geo = 6,
  APDRequest_FieldNumber_Ext = 7,
  APDRequest_FieldNumber_Impid = 8,
  APDRequest_FieldNumber_MainId = 9,
  APDRequest_FieldNumber_Get = 10,
  APDRequest_FieldNumber_Stats = 11,
  APDRequest_FieldNumber_Event = 12,
  APDRequest_FieldNumber_Timestamp = 13,
  APDRequest_FieldNumber_CustomState = 14,
  APDRequest_FieldNumber_ServicesData = 15,
};

/**
 * Unified request data
 **/
GPB_FINAL @interface APDRequest : GPBMessage

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDApp *app;
/** Test to see if @c app has been set. */
@property(nonatomic, readwrite) BOOL hasApp;

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDSession *session;
/** Test to see if @c session has been set. */
@property(nonatomic, readwrite) BOOL hasSession;

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDDevice *device;
/** Test to see if @c device has been set. */
@property(nonatomic, readwrite) BOOL hasDevice;

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDUser *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDRegs *regs;
/** Test to see if @c regs has been set. */
@property(nonatomic, readwrite) BOOL hasRegs;

/** *Required* */
@property(nonatomic, readwrite, strong, null_resettable) APDGeo *geo;
/** Test to see if @c geo has been set. */
@property(nonatomic, readwrite) BOOL hasGeo;

@property(nonatomic, readwrite, strong, null_resettable) APDExtra *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** ID of the impression *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *impid;

/** Waterfall main id *Required everywhere except Get request* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mainId;

/** Get request data */
@property(nonatomic, readwrite, strong, null_resettable) APDGet *get;
/** Test to see if @c get has been set. */
@property(nonatomic, readwrite) BOOL hasGet;

/** Stats request data */
@property(nonatomic, readwrite, strong, null_resettable) APDStats *stats;
/** Test to see if @c stats has been set. */
@property(nonatomic, readwrite) BOOL hasStats;

/** Show, Click, Finish event data */
@property(nonatomic, readwrite, strong, null_resettable) APDEvent *event;
/** Test to see if @c event has been set. */
@property(nonatomic, readwrite) BOOL hasEvent;

/** Request timestamp *Required* */
@property(nonatomic, readwrite) int64_t timestamp;

/** Custom state data passed from the app (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *customState;

/** Services request data */
@property(nonatomic, readwrite, strong, null_resettable) APDServices *servicesData;
/** Test to see if @c servicesData has been set. */
@property(nonatomic, readwrite) BOOL hasServicesData;

@end

#pragma mark - APDStats

typedef GPB_ENUM(APDStats_FieldNumber) {
  APDStats_FieldNumber_Capacity = 1,
  APDStats_FieldNumber_Start = 2,
  APDStats_FieldNumber_Finish = 3,
  APDStats_FieldNumber_Successful = 4,
  APDStats_FieldNumber_Completed = 5,
  APDStats_FieldNumber_AdUnitArray = 6,
  APDStats_FieldNumber_AdapterArray = 7,
};

/**
 * Stats request data
 **/
GPB_FINAL @interface APDStats : GPBMessage

/** Count of ads which we try to load *Required if > 1* */
@property(nonatomic, readwrite) int32_t capacity;

/** Timestamp of starting request *Required* */
@property(nonatomic, readwrite) int64_t start;

/** Timestamp of ending request *Required* */
@property(nonatomic, readwrite) int64_t finish;

/** Is current request was successful *Required* */
@property(nonatomic, readwrite) BOOL successful;

/** Is current request was completed or was stoped by impression *Required* */
@property(nonatomic, readwrite) BOOL completed;

/** Collection of ad unit statistics *Required* */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<APDStats_AdUnit*> *adUnitArray;
/** The number of items in @c adUnitArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adUnitArray_Count;

/** Collection of adapters used for PostBid *Required* */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<APDAdapter*> *adapterArray;
/** The number of items in @c adapterArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adapterArray_Count;

@end

#pragma mark - APDStats_AdUnit

typedef GPB_ENUM(APDStats_AdUnit_FieldNumber) {
  APDStats_AdUnit_FieldNumber_Id_p = 1,
  APDStats_AdUnit_FieldNumber_Start = 2,
  APDStats_AdUnit_FieldNumber_Finish = 3,
  APDStats_AdUnit_FieldNumber_Result = 4,
  APDStats_AdUnit_FieldNumber_Precache = 5,
  APDStats_AdUnit_FieldNumber_Ecpm = 6,
};

/**
 * Ad unit statistics
 **/
GPB_FINAL @interface APDStats_AdUnit : GPBMessage

/** Ad unit id *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** Timestamp of starting ad unit request *Required* */
@property(nonatomic, readwrite) int64_t start;

/** Timestamp of ending ad unti request *Required* */
@property(nonatomic, readwrite) int64_t finish;

/** *Required* */
@property(nonatomic, readwrite) APDStats_AdUnitRequestResult result;

/** Is ad unit was in precache waterfall *Required if true* */
@property(nonatomic, readwrite) BOOL precache;

/** Ecpm of the ad unit or price of the bid *Required* */
@property(nonatomic, readwrite) double ecpm;

@end

/**
 * Fetches the raw value of a @c APDStats_AdUnit's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDStats_AdUnit_Result_RawValue(APDStats_AdUnit *message);
/**
 * Sets the raw value of an @c APDStats_AdUnit's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDStats_AdUnit_Result_RawValue(APDStats_AdUnit *message, int32_t value);

#pragma mark - APDEvent

typedef GPB_ENUM(APDEvent_FieldNumber) {
  APDEvent_FieldNumber_EventType = 1,
  APDEvent_FieldNumber_Id_p = 2,
  APDEvent_FieldNumber_PlacementId = 3,
  APDEvent_FieldNumber_Currency = 4,
  APDEvent_FieldNumber_Amount = 5,
};

/**
 * Show, Click, Finish, Iap, Install request data
 **/
GPB_FINAL @interface APDEvent : GPBMessage

/**  *Required* */
@property(nonatomic, readwrite) APDEvent_EventType eventType;

/** Ad unit id  *Required* */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** Placement id */
@property(nonatomic, readwrite) int32_t placementId;

/** Reward currency */
@property(nonatomic, readwrite, copy, null_resettable) NSString *currency;

/** Reward amount */
@property(nonatomic, readwrite) float amount;

@end

/**
 * Fetches the raw value of a @c APDEvent's @c eventType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t APDEvent_EventType_RawValue(APDEvent *message);
/**
 * Sets the raw value of an @c APDEvent's @c eventType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAPDEvent_EventType_RawValue(APDEvent *message, int32_t value);

#pragma mark - APDGet

typedef GPB_ENUM(APDGet_FieldNumber) {
  APDGet_FieldNumber_Type = 1,
  APDGet_FieldNumber_LargeBanners = 2,
  APDGet_FieldNumber_RewardedVideo = 3,
  APDGet_FieldNumber_Debug = 4,
  APDGet_FieldNumber_ShowArrayArray = 5,
  APDGet_FieldNumber_CheckSdkVersion = 6,
};

/**
 * Get request data
 **/
GPB_FINAL @interface APDGet : GPBMessage

/** Ad type */
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/** Leader board required */
@property(nonatomic, readwrite) BOOL largeBanners;

/** Rewarded video */
@property(nonatomic, readwrite) BOOL rewardedVideo;

/** Debug request */
@property(nonatomic, readwrite) BOOL debug;

/** Array of ad networks names */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *showArrayArray;
/** The number of items in @c showArrayArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger showArrayArray_Count;

/** Should check sdk version */
@property(nonatomic, readwrite) BOOL checkSdkVersion GPB_DEPRECATED_MSG("com.appodeal.ads.Get.check_sdk_version is deprecated (see api.proto).");

@end

#pragma mark - APDServices

typedef GPB_ENUM(APDServices_FieldNumber) {
  APDServices_FieldNumber_Appsflyer = 1,
  APDServices_FieldNumber_Adjust = 2,
  APDServices_FieldNumber_Facebook = 3,
  APDServices_FieldNumber_Firebase = 4,
};

/**
 * Services request data
 **/
GPB_FINAL @interface APDServices : GPBMessage

/** Appsflyer service data */
@property(nonatomic, readwrite, strong, null_resettable) APDServices_Appsflyer *appsflyer;
/** Test to see if @c appsflyer has been set. */
@property(nonatomic, readwrite) BOOL hasAppsflyer;

/** Adjust service data */
@property(nonatomic, readwrite, strong, null_resettable) APDServices_Adjust *adjust;
/** Test to see if @c adjust has been set. */
@property(nonatomic, readwrite) BOOL hasAdjust;

/** Facebook service data */
@property(nonatomic, readwrite, strong, null_resettable) APDServices_Facebook *facebook;
/** Test to see if @c facebook has been set. */
@property(nonatomic, readwrite) BOOL hasFacebook;

/** Firebase service data */
@property(nonatomic, readwrite, strong, null_resettable) APDServices_Firebase *firebase;
/** Test to see if @c firebase has been set. */
@property(nonatomic, readwrite) BOOL hasFirebase;

@end

#pragma mark - APDServices_Appsflyer

typedef GPB_ENUM(APDServices_Appsflyer_FieldNumber) {
  APDServices_Appsflyer_FieldNumber_AttributionId = 1,
  APDServices_Appsflyer_FieldNumber_ConversionData = 2,
};

GPB_FINAL @interface APDServices_Appsflyer : GPBMessage

/** Appsflyer attribution Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *attributionId;

/** Conversion data passed from the app (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversionData;

@end

#pragma mark - APDServices_Adjust

typedef GPB_ENUM(APDServices_Adjust_FieldNumber) {
  APDServices_Adjust_FieldNumber_AttributionId = 1,
  APDServices_Adjust_FieldNumber_ConversionData = 2,
};

GPB_FINAL @interface APDServices_Adjust : GPBMessage

/** Adjust attribution Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *attributionId;

/** Conversion data passed from the app (serialized json object) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *conversionData;

@end

#pragma mark - APDServices_Facebook

typedef GPB_ENUM(APDServices_Facebook_FieldNumber) {
  APDServices_Facebook_FieldNumber_UserId = 1,
  APDServices_Facebook_FieldNumber_AppId = 2,
};

GPB_FINAL @interface APDServices_Facebook : GPBMessage

/** Facebook user Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

/** Facebook app Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@end

#pragma mark - APDServices_Firebase

typedef GPB_ENUM(APDServices_Firebase_FieldNumber) {
  APDServices_Firebase_FieldNumber_AppInstanceId = 1,
  APDServices_Firebase_FieldNumber_KeywordsArray = 2,
};

GPB_FINAL @interface APDServices_Firebase : GPBMessage

/** Firebase app instance Id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appInstanceId;

/** Comma joined list of values from remote config (Firebase Remote Config) */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *keywordsArray;
/** The number of items in @c keywordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger keywordsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
