// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/cache.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ADCOMPlacement;
@class BDMRequestTokenPayload_AppData;
@class BDMRequestTokenPayload_DeviceData;
@class BDMRequestTokenPayload_PlacementData;
@class BDMRequestTokenPayload_SessionData;
@class BDMRequestTokenPayload_SessionData_SessionPlacementData;
@class BDMRequestTokenPayload_UserData;
@class GPBTimestamp;
@class ORTBOpenrtb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BDMCacheRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BDMCacheRoot : GPBRootObject
@end

#pragma mark - BDMResponsePayload

typedef GPB_ENUM(BDMResponsePayload_FieldNumber) {
  BDMResponsePayload_FieldNumber_CacheTime = 1,
  BDMResponsePayload_FieldNumber_ResponseCacheURL = 2,
  BDMResponsePayload_FieldNumber_ResponseCache = 3,
  BDMResponsePayload_FieldNumber_RequestItemSpec = 4,
};

typedef GPB_ENUM(BDMResponsePayload_PayloadOneof_OneOfCase) {
  BDMResponsePayload_PayloadOneof_OneOfCase_GPBUnsetOneOfCase = 0,
  BDMResponsePayload_PayloadOneof_OneOfCase_ResponseCacheURL = 2,
  BDMResponsePayload_PayloadOneof_OneOfCase_ResponseCache = 3,
};

GPB_FINAL @interface BDMResponsePayload : GPBMessage

/** The time at which this payload cache was created */
@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *cacheTime;
/** Test to see if @c cacheTime has been set. */
@property(nonatomic, readwrite) BOOL hasCacheTime;

/**
 * Item spec (adcom.Placement in this case) from original openrtb.Request
 * Strictly it should be google.protobuf.Any as defined in openrtb.Request,
 * but for convenience reasons Layer-3 (Transaction) and Layer-4 (Domain) models are mixed here.
 **/
@property(nonatomic, readwrite, strong, null_resettable) ADCOMPlacement *requestItemSpec;
/** Test to see if @c requestItemSpec has been set. */
@property(nonatomic, readwrite) BOOL hasRequestItemSpec;

/**
 * Payload can be one of:
 *    - remotely cached response, accessible via provided cache URL
 *    - actual Response cache
 **/
@property(nonatomic, readonly) BDMResponsePayload_PayloadOneof_OneOfCase payloadOneofOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *responseCacheURL;

@property(nonatomic, readwrite, strong, null_resettable) ORTBOpenrtb *responseCache;

@end

/**
 * Clears whatever value was set for the oneof 'payloadOneof'.
 **/
void BDMResponsePayload_ClearPayloadOneofOneOfCase(BDMResponsePayload *message);

#pragma mark - BDMRequestTokenPayload

typedef GPB_ENUM(BDMRequestTokenPayload_FieldNumber) {
  BDMRequestTokenPayload_FieldNumber_PlacementData = 1,
  BDMRequestTokenPayload_FieldNumber_SessionData = 2,
  BDMRequestTokenPayload_FieldNumber_DeviceData = 3,
  BDMRequestTokenPayload_FieldNumber_CustomData = 4,
  BDMRequestTokenPayload_FieldNumber_UserData = 5,
  BDMRequestTokenPayload_FieldNumber_AppData = 6,
};

GPB_FINAL @interface BDMRequestTokenPayload : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BDMRequestTokenPayload_PlacementData *placementData;
/** Test to see if @c placementData has been set. */
@property(nonatomic, readwrite) BOOL hasPlacementData;

@property(nonatomic, readwrite, strong, null_resettable) BDMRequestTokenPayload_SessionData *sessionData;
/** Test to see if @c sessionData has been set. */
@property(nonatomic, readwrite) BOOL hasSessionData;

@property(nonatomic, readwrite, strong, null_resettable) BDMRequestTokenPayload_DeviceData *deviceData;
/** Test to see if @c deviceData has been set. */
@property(nonatomic, readwrite) BOOL hasDeviceData;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *customData;
/** The number of items in @c customData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger customData_Count;

@property(nonatomic, readwrite, strong, null_resettable) BDMRequestTokenPayload_UserData *userData;
/** Test to see if @c userData has been set. */
@property(nonatomic, readwrite) BOOL hasUserData;

@property(nonatomic, readwrite, strong, null_resettable) BDMRequestTokenPayload_AppData *appData;
/** Test to see if @c appData has been set. */
@property(nonatomic, readwrite) BOOL hasAppData;

@end

#pragma mark - BDMRequestTokenPayload_PlacementData

typedef GPB_ENUM(BDMRequestTokenPayload_PlacementData_FieldNumber) {
  BDMRequestTokenPayload_PlacementData_FieldNumber_Sdk = 1,
  BDMRequestTokenPayload_PlacementData_FieldNumber_Sdkver = 2,
};

GPB_FINAL @interface BDMRequestTokenPayload_PlacementData : GPBMessage

/** Name of ad mediation partner, SDK technology, or player responsible for rendering ad. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdk;

/** Version of the SDK specified in the "sdk" attribute. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkver;

@end

#pragma mark - BDMRequestTokenPayload_SessionData

typedef GPB_ENUM(BDMRequestTokenPayload_SessionData_FieldNumber) {
  BDMRequestTokenPayload_SessionData_FieldNumber_SessionId = 1,
  BDMRequestTokenPayload_SessionData_FieldNumber_Sessionduration = 2,
  BDMRequestTokenPayload_SessionData_FieldNumber_SessionPlacementData = 3,
};

GPB_FINAL @interface BDMRequestTokenPayload_SessionData : GPBMessage

/** Session ID - consistent between requests as long as application active (on screen) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** The total duration of time a user has spent so far in a specific app session expressed in seconds */
@property(nonatomic, readwrite) uint64_t sessionduration;

/** Placement keys: banner, interstitial, rewarded, native, richmedia */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, BDMRequestTokenPayload_SessionData_SessionPlacementData*> *sessionPlacementData;
/** The number of items in @c sessionPlacementData without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sessionPlacementData_Count;

@end

#pragma mark - BDMRequestTokenPayload_SessionData_SessionPlacementData

typedef GPB_ENUM(BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber) {
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Impdepth = 1,
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Lastbundle = 3,
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Lastadomain = 4,
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Clickrate = 5,
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Lastclick = 6,
  BDMRequestTokenPayload_SessionData_SessionPlacementData_FieldNumber_Completionrate = 7,
};

GPB_FINAL @interface BDMRequestTokenPayload_SessionData_SessionPlacementData : GPBMessage

/**
 * The count of impressions for a specific placement type in a given app session.
 * The impression depth is reset once the session ends
 **/
@property(nonatomic, readwrite) uint32_t impdepth;

/** The last app bundle the user saw on the previous impression in a given session per placement type */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastbundle;

/** The last advertiser domain the user saw on the previous impression in a given session per placement type */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lastadomain;

/**
 * The percentage of clicks/impressions per user per placement type
 * over a given number of impressions in a given session,
 * where 0.05 represents a 5% click rate
 **/
@property(nonatomic, readwrite) float clickrate;

/**
 * An bool value indicating if the user clicked on the last impression
 * in a given session per placement type
 **/
@property(nonatomic, readwrite) BOOL lastclick;

/**
 * The percentage of successful completions /impressions for a user per placement type
 * for a given number of impressions in a given session,
 * where 0.7 represents a 70% completion rate.
 * This only applies to Rewarded and Video placement types
 **/
@property(nonatomic, readwrite) float completionrate;

@end

#pragma mark - BDMRequestTokenPayload_DeviceData

typedef GPB_ENUM(BDMRequestTokenPayload_DeviceData_FieldNumber) {
  BDMRequestTokenPayload_DeviceData_FieldNumber_Ifv = 1,
  BDMRequestTokenPayload_DeviceData_FieldNumber_BmIfv = 2,
  BDMRequestTokenPayload_DeviceData_FieldNumber_InputlanguageArray = 3,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Diskspace = 4,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Totaldisk = 5,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Ringmute = 6,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Charging = 7,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Headset = 8,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Batterylevel = 9,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Batterysaver = 10,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Darkmode = 11,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Airplane = 12,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Dnd = 13,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Devicename = 14,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Time = 15,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Screenbright = 16,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Jailbreak = 17,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Lastbootup = 18,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Access = 19,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Headsetname = 20,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Totalmem = 21,
  BDMRequestTokenPayload_DeviceData_FieldNumber_Atts = 22,
};

GPB_FINAL @interface BDMRequestTokenPayload_DeviceData : GPBMessage

/** An alphanumeric string that uniquely identifies a device to the app’s vendor. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ifv;

/** BidMachine specific alphanumeric string that uniquely identifies a device. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bmIfv;

/**
 * A string array containing the languages set up on the user's device keyboard.
 * Country codes are passed in the string array,
 * where "en", "he" = English and Hebrew languages are enabled on the user's device keyboard
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *inputlanguageArray;
/** The number of items in @c inputlanguageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger inputlanguageArray_Count;

/**
 * An integer value describing the available disk space on the device in megabytes,
 * where "18201" = device has 18201 MB of available disk space.
 * MB will be passed as a whole number.
 **/
@property(nonatomic, readwrite) uint64_t diskspace;

/**
 * An integer value describing the total disk space on the device in megabytes,
 * where "63989" = the device has 63989 MB of total disk space.
 * MB will be passed as a whole number.
 **/
@property(nonatomic, readwrite) uint64_t totaldisk;

/**
 *  (Android only)
 *  A bool value describing the device sound setting during the time of the ad request
 *  describing if the sound is set to ring or mute, where "false" = mute, "true" = ring
 **/
@property(nonatomic, readwrite) BOOL ringmute;

/** A bool value describing if the device is connected to a charger */
@property(nonatomic, readwrite) BOOL charging;

/** A bool value indicating if the device is connected to a wired headset */
@property(nonatomic, readwrite) BOOL headset;

/** An float describing percent battery remaining on the user's device */
@property(nonatomic, readwrite) float batterylevel;

/** A bool value indicating if battery saver ('Low Power Mode' on iOS) has been enabled */
@property(nonatomic, readwrite) BOOL batterysaver;

/** A bool value indicating if dark mode is enabled on the device */
@property(nonatomic, readwrite) BOOL darkmode;

/**
 * (Android only)
 * A bool value indicating if airplane mode is enabled
 **/
@property(nonatomic, readwrite) BOOL airplane;

/**
 * (Android only)
 * A bool value indicating if do not disturb setting is enabled
 **/
@property(nonatomic, readwrite) BOOL dnd;

/** A value indicating the device name */
@property(nonatomic, readwrite, copy, null_resettable) NSString *devicename;

/** POSIX timestamp. Depends on device time settings. */
@property(nonatomic, readwrite) uint64_t time;

/**
 * A value in the range from 0.0 to 1.0 to represent the brightness level
 * of the main screen of the device.
 **/
@property(nonatomic, readwrite) float screenbright;

/** A bool value indicating if a device was jailbroken */
@property(nonatomic, readwrite) BOOL jailbreak;

/**
 * POSIX timestamp of latest device boot with accuracy in seconds.
 * Depends on device time settings
 **/
@property(nonatomic, readwrite) uint64_t lastbootup;

/**
 * User's accessibilities features. The sequence of "1" and 0" there
 * every number means that some feature is enabled or not
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *access;

/** Identifier of connected wireless audio headset */
@property(nonatomic, readwrite, copy, null_resettable) NSString *headsetname;

/** Total devices RAM in bytes */
@property(nonatomic, readwrite) uint64_t totalmem;

/**
 * (iOS Only)
 * A value indicating the status of app tracking authorization.
 * Possible values:
 *   0 = not determined
 *   1 = restricted
 *   2 = denied
 *   3 = authorized
 **/
@property(nonatomic, readwrite) uint32_t atts;

@end

#pragma mark - BDMRequestTokenPayload_UserData

typedef GPB_ENUM(BDMRequestTokenPayload_UserData_FieldNumber) {
  BDMRequestTokenPayload_UserData_FieldNumber_Consent = 1,
  BDMRequestTokenPayload_UserData_FieldNumber_Gdpr = 2,
  BDMRequestTokenPayload_UserData_FieldNumber_Ccpa = 3,
};

GPB_FINAL @interface BDMRequestTokenPayload_UserData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *consent;

@property(nonatomic, readwrite) BOOL gdpr;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ccpa;

@end

#pragma mark - BDMRequestTokenPayload_AppData

typedef GPB_ENUM(BDMRequestTokenPayload_AppData_FieldNumber) {
  BDMRequestTokenPayload_AppData_FieldNumber_AppName = 1,
  BDMRequestTokenPayload_AppData_FieldNumber_AppVer = 2,
};

GPB_FINAL @interface BDMRequestTokenPayload_AppData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appVer;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
