// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/headerbidding/headerbidding.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BDMHeaderBiddingPlacement_AdUnit;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BDMHeaderbiddingRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BDMHeaderbiddingRoot : GPBRootObject
@end

#pragma mark - BDMHeaderBiddingPlacement

typedef GPB_ENUM(BDMHeaderBiddingPlacement_FieldNumber) {
  BDMHeaderBiddingPlacement_FieldNumber_AdUnitsArray = 1,
};

/**
 * adcom.Placement Object Extension
 **/
GPB_FINAL @interface BDMHeaderBiddingPlacement : GPBMessage

/** Third-party ad units list */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BDMHeaderBiddingPlacement_AdUnit*> *adUnitsArray;
/** The number of items in @c adUnitsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adUnitsArray_Count;

@end

#pragma mark - BDMHeaderBiddingPlacement_AdUnit

typedef GPB_ENUM(BDMHeaderBiddingPlacement_AdUnit_FieldNumber) {
  BDMHeaderBiddingPlacement_AdUnit_FieldNumber_Bidder = 1,
  BDMHeaderBiddingPlacement_AdUnit_FieldNumber_BidderSdkver = 2,
  BDMHeaderBiddingPlacement_AdUnit_FieldNumber_ClientParams = 3,
  BDMHeaderBiddingPlacement_AdUnit_FieldNumber_PriceEstimate = 4,
};

GPB_FINAL @interface BDMHeaderBiddingPlacement_AdUnit : GPBMessage

/** Bidder SDK technology */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bidder;

/** Bidder SDK version (for analytics only) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bidderSdkver;

/** Custom params obtained on client from Bidder SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *clientParams;
/** The number of items in @c clientParams without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clientParams_Count;

/** Estimated price, calculated externally */
@property(nonatomic, readwrite) double priceEstimate;

@end

#pragma mark - BDMHeaderBiddingAd

typedef GPB_ENUM(BDMHeaderBiddingAd_FieldNumber) {
  BDMHeaderBiddingAd_FieldNumber_Bidder = 1,
  BDMHeaderBiddingAd_FieldNumber_ClientParams = 2,
  BDMHeaderBiddingAd_FieldNumber_ServerParams = 3,
};

/**
 * adcom.Ad Object Extension
 **/
GPB_FINAL @interface BDMHeaderBiddingAd : GPBMessage

/** Bidder SDK technology */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bidder;

/** Custom params from AdUnit.client_params back-propagated to client */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *clientParams;
/** The number of items in @c clientParams without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger clientParams_Count;

/** Params obtained on Bidder Server to feed in Bidder SDK technology */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *serverParams;
/** The number of items in @c serverParams without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger serverParams_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
