// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/init.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ADCOMAd_Event;
@class ADCOMContext_Geo;
@class BDMAdCachePlacementControl;
@class BDMAdNetwork;
@class BDMAdNetwork_AdUnit;
@class GPBStruct;
GPB_ENUM_FWD_DECLARE(ADCOMConnectionType);
GPB_ENUM_FWD_DECLARE(ADCOMDeviceType);
GPB_ENUM_FWD_DECLARE(ADCOMOS);
GPB_ENUM_FWD_DECLARE(BDMAdCacheControl);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BDMInitRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BDMInitRoot : GPBRootObject
@end

#pragma mark - BDMInitRequest

typedef GPB_ENUM(BDMInitRequest_FieldNumber) {
  BDMInitRequest_FieldNumber_SellerId = 1,
  BDMInitRequest_FieldNumber_Bundle = 2,
  BDMInitRequest_FieldNumber_Os = 3,
  BDMInitRequest_FieldNumber_Osv = 4,
  BDMInitRequest_FieldNumber_Geo = 5,
  BDMInitRequest_FieldNumber_Sdk = 6,
  BDMInitRequest_FieldNumber_Sdkver = 7,
  BDMInitRequest_FieldNumber_Ifa = 8,
  BDMInitRequest_FieldNumber_DeviceType = 9,
  BDMInitRequest_FieldNumber_Contype = 10,
  BDMInitRequest_FieldNumber_Ifv = 11,
  BDMInitRequest_FieldNumber_BmIfv = 12,
  BDMInitRequest_FieldNumber_AppVer = 13,
  BDMInitRequest_FieldNumber_SessionId = 14,
  BDMInitRequest_FieldNumber_Ext = 15,
};

GPB_FINAL @interface BDMInitRequest : GPBMessage

/** Exchange Source ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sellerId;

/** Bundle or package name of the app. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bundle;

/** Device operating system. */
@property(nonatomic, readwrite) enum ADCOMOS os;

/** Device operating system version. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osv;

/** Location of the device. */
@property(nonatomic, readwrite, strong, null_resettable) ADCOMContext_Geo *geo;
/** Test to see if @c geo has been set. */
@property(nonatomic, readwrite) BOOL hasGeo;

/** Name of ad mediation partner, SDK technology, or player responsible for rendering ad. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdk;

/** Version of the SDK specified in the "sdk" attribute. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkver;

/** ID sanctioned for advertiser use in the clear (i.e., not hashed). */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ifa;

/** ID generated by the OS on device for debug and fraud detection */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ifv;

/** ID generated on device for debug and fraud detection */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bmIfv;

/** The general type of device. */
@property(nonatomic, readwrite) enum ADCOMDeviceType deviceType;

/** Network connection type. */
@property(nonatomic, readwrite) enum ADCOMConnectionType contype;

/** Application version. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appVer;

/** Session ID - consistent between requests as long as application active (on screen) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** Optional extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

@end

/**
 * Fetches the raw value of a @c BDMInitRequest's @c os property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_Os_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c os property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_Os_RawValue(BDMInitRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c BDMInitRequest's @c deviceType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_DeviceType_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c deviceType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_DeviceType_RawValue(BDMInitRequest *message, int32_t value);

/**
 * Fetches the raw value of a @c BDMInitRequest's @c contype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitRequest_Contype_RawValue(BDMInitRequest *message);
/**
 * Sets the raw value of an @c BDMInitRequest's @c contype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitRequest_Contype_RawValue(BDMInitRequest *message, int32_t value);

#pragma mark - BDMAdNetwork

typedef GPB_ENUM(BDMAdNetwork_FieldNumber) {
  BDMAdNetwork_FieldNumber_Name = 1,
  BDMAdNetwork_FieldNumber_ClassName_p = 2,
  BDMAdNetwork_FieldNumber_CustomParams = 3,
  BDMAdNetwork_FieldNumber_AdUnitsArray = 4,
};

GPB_FINAL @interface BDMAdNetwork : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *className_p;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *customParams;
/** The number of items in @c customParams without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger customParams_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BDMAdNetwork_AdUnit*> *adUnitsArray;
/** The number of items in @c adUnitsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adUnitsArray_Count;

@end

#pragma mark - BDMAdNetwork_AdUnit

typedef GPB_ENUM(BDMAdNetwork_AdUnit_FieldNumber) {
  BDMAdNetwork_AdUnit_FieldNumber_AdFormat = 1,
  BDMAdNetwork_AdUnit_FieldNumber_CustomParams = 2,
};

GPB_FINAL @interface BDMAdNetwork_AdUnit : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *adFormat;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *customParams;
/** The number of items in @c customParams without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger customParams_Count;

@end

#pragma mark - BDMAdCachePlacementControl

typedef GPB_ENUM(BDMAdCachePlacementControl_FieldNumber) {
  BDMAdCachePlacementControl_FieldNumber_MaxCacheSize = 2,
  BDMAdCachePlacementControl_FieldNumber_MaxAge = 3,
  BDMAdCachePlacementControl_FieldNumber_MaxRetainCount = 4,
};

GPB_FINAL @interface BDMAdCachePlacementControl : GPBMessage

@property(nonatomic, readwrite) uint32_t maxCacheSize;

@property(nonatomic, readwrite) uint32_t maxRetainCount;

@property(nonatomic, readwrite) uint32_t maxAge;

@end

#pragma mark - BDMInitResponse

typedef GPB_ENUM(BDMInitResponse_FieldNumber) {
  BDMInitResponse_FieldNumber_Endpoint = 1,
  BDMInitResponse_FieldNumber_EventArray = 2,
  BDMInitResponse_FieldNumber_SessionResetAfter = 3,
  BDMInitResponse_FieldNumber_AdNetworksArray = 4,
  BDMInitResponse_FieldNumber_AdCacheControl = 5,
  BDMInitResponse_FieldNumber_AdCacheMaxAge = 6,
  BDMInitResponse_FieldNumber_AdRequestTmax = 7,
  BDMInitResponse_FieldNumber_AdCachePlacementControl = 8,
  BDMInitResponse_FieldNumber_AdNetworksLoadingTimeout = 9,
};

GPB_FINAL @interface BDMInitResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *endpoint;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ADCOMAd_Event*> *eventArray;
/** The number of items in @c eventArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventArray_Count;

@property(nonatomic, readwrite) uint32_t sessionResetAfter;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BDMAdNetwork*> *adNetworksArray;
/** The number of items in @c adNetworksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adNetworksArray_Count;

/** Third party ad network adapters global loading timeout in seconds */
@property(nonatomic, readwrite) uint32_t adNetworksLoadingTimeout;

@property(nonatomic, readwrite) enum BDMAdCacheControl adCacheControl;

@property(nonatomic, readwrite) uint32_t adCacheMaxAge;

/** Placement keys: banner, interstitial, rewarded, native, richmedia */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, BDMAdCachePlacementControl*> *adCachePlacementControl;
/** The number of items in @c adCachePlacementControl without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger adCachePlacementControl_Count;

@property(nonatomic, readwrite) uint32_t adRequestTmax;

@end

/**
 * Fetches the raw value of a @c BDMInitResponse's @c adCacheControl property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t BDMInitResponse_AdCacheControl_RawValue(BDMInitResponse *message);
/**
 * Sets the raw value of an @c BDMInitResponse's @c adCacheControl property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetBDMInitResponse_AdCacheControl_RawValue(BDMInitResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
