// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bidmachine/protobuf/openrtb/openrtb.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBAny;
@class GPBStruct;
@class ORTBRequest;
@class ORTBRequest_Item;
@class ORTBRequest_Item_Deal;
@class ORTBRequest_Item_Metric;
@class ORTBRequest_Source;
@class ORTBResponse;
@class ORTBResponse_Seatbid;
@class ORTBResponse_Seatbid_Bid;
@class ORTBResponse_Seatbid_Bid_Macro;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ORTBNoBidReason

/**
 * The following table lists the options for a bidder to signal
 * the exchange as to why it did not offer a bid for the item.
 **/
typedef GPB_ENUM(ORTBNoBidReason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ORTBNoBidReason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ORTBNoBidReason_NoBidReasonInvalid = 0,
  ORTBNoBidReason_NoBidReasonTechnicalError = 1,
  ORTBNoBidReason_NoBidReasonInvalidRequest = 2,
  ORTBNoBidReason_NoBidReasonKnownWebCrawler = 3,
  ORTBNoBidReason_NoBidReasonNonHumanTraffic = 4,
  ORTBNoBidReason_NoBidReasonProxyIp = 5,
  ORTBNoBidReason_NoBidReasonUnsupportedDevice = 6,
  ORTBNoBidReason_NoBidReasonBlocked = 7,
  ORTBNoBidReason_NoBidReasonUnmatchedUser = 8,
  ORTBNoBidReason_NoBidReasonDailyUserCapMet = 9,
  ORTBNoBidReason_NoBidReasonDailyDomainCapMet = 10,
  ORTBNoBidReason_NoBidReasonAdsTxtAuthorizationUnavailable = 11,
  ORTBNoBidReason_NoBidReasonAdsTxtAuthorizationViolation = 12,
  ORTBNoBidReason_NoBidReasonAdsCertAuthenticationUnavailable = 13,
  ORTBNoBidReason_NoBidReasonAdsCertAuthenticationViolation = 14,
  ORTBNoBidReason_NoBidReasonInsufficientAuctionTime = 15,
};

GPBEnumDescriptor *ORTBNoBidReason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ORTBNoBidReason_IsValidValue(int32_t value);

#pragma mark - Enum ORTBLossReason

/**
 * The following table lists the options for an exchange to inform
 * a bidder as to the reason why they did not win an item.
 **/
typedef GPB_ENUM(ORTBLossReason) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ORTBLossReason_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ORTBLossReason_LossReasonBidWon = 0,
  ORTBLossReason_LossReasonInternalError = 1,
  ORTBLossReason_LossReasonImpressionOpportunityExpired = 2,
  ORTBLossReason_LossReasonInvalidBidResponse = 3,
  ORTBLossReason_LossReasonInvalidDealId = 4,
  ORTBLossReason_LossReasonInvalidAuctionId = 5,
  ORTBLossReason_LossReasonInvalidAdvertiserDomain = 6,
  ORTBLossReason_LossReasonMissingMarkup = 7,
  ORTBLossReason_LossReasonMissingCreativeId = 8,
  ORTBLossReason_LossReasonMissingBidPrice = 9,
  ORTBLossReason_LossReasonMissingCreativeApprovalData = 10,
  ORTBLossReason_LossReasonBelowAuctionFloor = 100,
  ORTBLossReason_LossReasonBelowDealFloor = 101,
  ORTBLossReason_LossReasonLostToHigherBid = 102,
  ORTBLossReason_LossReasonLostToADeal = 103,
  ORTBLossReason_LossReasonSeatBlocked = 104,
  ORTBLossReason_LossReasonCreativeFilteredGeneral = 200,
  ORTBLossReason_LossReasonCreativeFilteredPendingProcessing = 201,
  ORTBLossReason_LossReasonCreativeFilteredDisapproved = 202,
  ORTBLossReason_LossReasonCreativeFilteredSizeNotAllowed = 203,
  ORTBLossReason_LossReasonCreativeFilteredIncorrectCreativeFormat = 204,
  ORTBLossReason_LossReasonCreativeFilteredAdvertiserExclusions = 205,
  ORTBLossReason_LossReasonCreativeFilteredNotSecure = 206,
  ORTBLossReason_LossReasonCreativeFilteredLanguageExclusions = 207,
  ORTBLossReason_LossReasonCreativeFilteredCategoryExclusions = 208,
  ORTBLossReason_LossReasonCreativeFilteredCreativeAttributeExclusions = 209,
  ORTBLossReason_LossReasonCreativeFilteredAdTypeExclusions = 210,
  ORTBLossReason_LossReasonCreativeFilteredAnimationTooLong = 211,
  ORTBLossReason_LossReasonCreativeFilteredNotAllowedInDeal = 212,
};

GPBEnumDescriptor *ORTBLossReason_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ORTBLossReason_IsValidValue(int32_t value);

#pragma mark - ORTBOpenrtbRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ORTBOpenrtbRoot : GPBRootObject
@end

#pragma mark - ORTBOpenrtb

typedef GPB_ENUM(ORTBOpenrtb_FieldNumber) {
  ORTBOpenrtb_FieldNumber_Ver = 1,
  ORTBOpenrtb_FieldNumber_Domainspec = 2,
  ORTBOpenrtb_FieldNumber_Domainver = 3,
  ORTBOpenrtb_FieldNumber_Request = 4,
  ORTBOpenrtb_FieldNumber_Response = 5,
};

typedef GPB_ENUM(ORTBOpenrtb_Payload_OneOfCase) {
  ORTBOpenrtb_Payload_OneOfCase_GPBUnsetOneOfCase = 0,
  ORTBOpenrtb_Payload_OneOfCase_Request = 4,
  ORTBOpenrtb_Payload_OneOfCase_Response = 5,
};

/**
 * This top-level object is the root for both request and response payloads.
 * It includes versioning information and references to the Layer-4 domain model
 * on which transactions are based. By default, the domain model used by OpenRTB
 * is the Advertising Common Object Model (AdCOM).
 **/
GPB_FINAL @interface ORTBOpenrtb : GPBMessage

/** Version of the Layer-3 OpenRTB specification (e.g., "3.0"). */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ver;

/**
 * Identifier of the Layer-4 domain model.
 * \@default "adcom"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *domainspec;

/**
 * Specification version of the Layer-4 domain model referenced in the “domainspec” attribute.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *domainver;

@property(nonatomic, readonly) ORTBOpenrtb_Payload_OneOfCase payloadOneOfCase;

/**
 * Bid request container.
 * \@required*
 **/
@property(nonatomic, readwrite, strong, null_resettable) ORTBRequest *request;

/**
 * Bid response container.
 * \@required*
 **/
@property(nonatomic, readwrite, strong, null_resettable) ORTBResponse *response;

@end

/**
 * Clears whatever value was set for the oneof 'payload'.
 **/
void ORTBOpenrtb_ClearPayloadOneOfCase(ORTBOpenrtb *message);

#pragma mark - ORTBRequest

typedef GPB_ENUM(ORTBRequest_FieldNumber) {
  ORTBRequest_FieldNumber_Id_p = 1,
  ORTBRequest_FieldNumber_Test = 2,
  ORTBRequest_FieldNumber_Tmax = 3,
  ORTBRequest_FieldNumber_At = 4,
  ORTBRequest_FieldNumber_CurArray = 5,
  ORTBRequest_FieldNumber_SeatArray = 6,
  ORTBRequest_FieldNumber_Wseat = 7,
  ORTBRequest_FieldNumber_Cdata = 8,
  ORTBRequest_FieldNumber_Source = 9,
  ORTBRequest_FieldNumber_ItemArray = 10,
  ORTBRequest_FieldNumber_Package = 11,
  ORTBRequest_FieldNumber_Context = 12,
  ORTBRequest_FieldNumber_ExtProtoArray = 13,
  ORTBRequest_FieldNumber_Ext = 14,
};

/**
 * The Request object contains a globally unique bid request ID.
 * This id attribute is required as is an Item array with at least
 * one object (i.e., at least one item for sale).
 * Other attributes establish rules and restrictions that apply to all items being offered.
 **/
GPB_FINAL @interface ORTBRequest : GPBMessage

/** Unique ID of the bid request; provided by the exchange. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/**
 * Indicator of test mode in which auctions are not billable,
 * where false = live mode, true = test mode.
 * \@default false
 **/
@property(nonatomic, readwrite) BOOL test;

/**
 * Maximum time in milliseconds the exchange allows for bids to be
 * received including Internet latency to avoid timeout.
 **/
@property(nonatomic, readwrite) uint32_t tmax;

/**
 * Auction type, where 1 = First Price, 2 = Second Price Plus.
 * Values greater than 500 can be used for exchange-specific auction types.
 * \@default 2
 **/
@property(nonatomic, readwrite) uint32_t at;

/**
 * Array of accepted currencies for bids on this bid request
 * using ISO-4217 alpha codes.
 * \@default ["USD"]
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *curArray;
/** The number of items in @c curArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger curArray_Count;

/** Restriction list of buyer seats for bidding on this item. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *seatArray;
/** The number of items in @c seatArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger seatArray_Count;

/**
 * Flag that determines the restriction interpretation of the “seat” array,
 * where false = block list, true = whitelist.
 * \@default true
 **/
@property(nonatomic, readwrite) BOOL wseat;

/**
 * Allows bidder to retrieve data set on its behalf in the exchange’s cookie.
 * The string must be in base85 cookie-safe characters.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *cdata;

/**
 * A “Source” object that provides data about the inventory source
 * and which entity makes the final decision.
 **/
@property(nonatomic, readwrite, strong, null_resettable) ORTBRequest_Source *source;
/** Test to see if @c source has been set. */
@property(nonatomic, readwrite) BOOL hasSource;

/**
 * Array of “Item” objects (at least one) that constitute
 * the set of goods being offered for sale.
 * \@required
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBRequest_Item*> *itemArray;
/** The number of items in @c itemArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemArray_Count;

/**
 * Flag to indicate if the Exchange can verify that the items
 * offered represent all of the items available in context.
 **/
@property(nonatomic, readwrite) uint32_t package;

/**
 * Layer-4 domain object structure that provides context for the items
 * being offered conforming to the specification and version referenced
 * in “openrtb.domainspec” and “openrtb.domainver”.
 * For AdCOM v1.x, the objects allowed here all of which are optional are
 * one of the “DistributionChannel” subtypes (i.e., “Site”, “App”, or “Dooh”),
 * “User”, “Device”, “Regs”, and any objects subordinate to these as specified by AdCOM.
 * \@recommended
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *context;
/** Test to see if @c context has been set. */
@property(nonatomic, readwrite) BOOL hasContext;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBRequest_Source

typedef GPB_ENUM(ORTBRequest_Source_FieldNumber) {
  ORTBRequest_Source_FieldNumber_Tid = 1,
  ORTBRequest_Source_FieldNumber_Ds = 2,
  ORTBRequest_Source_FieldNumber_Dsgver = 3,
  ORTBRequest_Source_FieldNumber_Digest = 4,
  ORTBRequest_Source_FieldNumber_Cert = 5,
  ORTBRequest_Source_FieldNumber_Pchain = 6,
  ORTBRequest_Source_FieldNumber_ExtProtoArray = 7,
  ORTBRequest_Source_FieldNumber_Ext = 8,
};

/**
 * This object carries data about the source of the transaction
 * including the unique ID of the transaction itself,
 * source authentication information, and the chain of custody.
 **/
GPB_FINAL @interface ORTBRequest_Source : GPBMessage

/**
 * Transaction ID that must be common across all participants throughout
 * the entire supply chain of this transaction.
 * This also applies across all participating exchanges
 * in a header bidding or similar publisher-centric broadcast scenario.
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *tid;

/**
 * Digital signature used to authenticate this request computed by the publisher
 * or its trusted agent from the transaction digest string "tid:digest",
 * where ‘tid’ matches the "tid" attribute and ‘digest’ is a string
 * composed of an immutable portion of domain objects as defined
 * in the domain specification used for this request.
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *ds;

/**
 * Format version of the digest string that was digitally signed to produce “ds”.
 * \@recommended
 **/
@property(nonatomic, readwrite) uint32_t dsgver;

/**
 * The full transaction digest string that was signed to produce the digital signature.
 * \@debug
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *digest;

/**
 * File name of the certificate (i.e., the public key) used
 * to generate the digital signature in “ds” attribute.\\
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *cert;

/**
 * Payment ID chain string containing embedded syntax described
 * in the TAG Payment ID Protocol. NOTE that the authentication
 * features in this Source object combined with the “ads.txt”
 * specification may lead to the future deprecation of this attribute.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *pchain;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBRequest_Item

typedef GPB_ENUM(ORTBRequest_Item_FieldNumber) {
  ORTBRequest_Item_FieldNumber_Id_p = 1,
  ORTBRequest_Item_FieldNumber_Qty = 2,
  ORTBRequest_Item_FieldNumber_Seq = 3,
  ORTBRequest_Item_FieldNumber_Flr = 4,
  ORTBRequest_Item_FieldNumber_Flrcur = 6,
  ORTBRequest_Item_FieldNumber_Exp = 7,
  ORTBRequest_Item_FieldNumber_Dt = 8,
  ORTBRequest_Item_FieldNumber_Dlvy = 9,
  ORTBRequest_Item_FieldNumber_MetricArray = 10,
  ORTBRequest_Item_FieldNumber_DealArray = 11,
  ORTBRequest_Item_FieldNumber_Private_p = 12,
  ORTBRequest_Item_FieldNumber_Spec = 13,
  ORTBRequest_Item_FieldNumber_ExtProtoArray = 14,
  ORTBRequest_Item_FieldNumber_Ext = 15,
};

/**
 * This object represents a unit of goods being offered for sale either
 * on the open market or in relation to a private marketplace deal.
 * The id attribute is required since there may be multiple items being
 * offered in the same bid request and bids must reference the specific item of interest.
 **/
GPB_FINAL @interface ORTBRequest_Item : GPBMessage

/**
 * A unique identifier for this item within the context of the offer.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/**
 * The number of instances (i.e., "quantity") of this item being offered.
 * \@default 1
 **/
@property(nonatomic, readwrite) uint32_t qty;

/**
 * If multiple items are offered in the same bid request,
 * the sequence number allows for the coordinated delivery.
 **/
@property(nonatomic, readwrite) uint32_t seq;

/** Minimum bid price for this item expressed in CPM. */
@property(nonatomic, readwrite) double flr;

/**
 * Currency of the “flr” attribute specified using
 * ISO-4217 alpha codes.
 * \@default "USD"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *flrcur;

/**
 * Advisory as to the number of seconds that may elapse
 * between auction and fulfilment.
 **/
@property(nonatomic, readwrite) uint32_t exp;

/**
 * Date/time when the item is expected to be fulfilled
 * using the W3C-defined ISO-8601 format.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *dt;

/**
 * Item (e.g., an Ad object) delivery method required,
 * where 0 = either method, 1 = the item must be sent as part of the transaction,
 * and 2 = an item previously uploaded to the exchange must be referenced by its ID.
 * \@default 0
 **/
@property(nonatomic, readwrite) uint32_t dlvy;

/** An array of “Metric” objects. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBRequest_Item_Metric*> *metricArray;
/** The number of items in @c metricArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger metricArray_Count;

/** Array of “Deal” objects that convey special terms applicable to this item. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBRequest_Item_Deal*> *dealArray;
/** The number of items in @c dealArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger dealArray_Count;

/**
 * Indicator of auction eligibility to seats named in “Deal” objects,
 * where false = all bids are accepted, true = bids are restricted
 * to the deals specified and the terms thereof.
 * \@default false
 **/
@property(nonatomic, readwrite) BOOL private_p;

/**
 * Layer-4 domain object structure that provides specifies the item
 * being offered conforming to the specification and version referenced
 * in “openrtb.domainspec” and “openrtb.domainver”.
 * For AdCOM v1.x, the objects allowed here are “Placement” and
 * any objects subordinate to these as specified by AdCOM.
 * \@required
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *spec;
/** Test to see if @c spec has been set. */
@property(nonatomic, readwrite) BOOL hasSpec;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBRequest_Item_Metric

typedef GPB_ENUM(ORTBRequest_Item_Metric_FieldNumber) {
  ORTBRequest_Item_Metric_FieldNumber_Type = 1,
  ORTBRequest_Item_Metric_FieldNumber_Value = 2,
  ORTBRequest_Item_Metric_FieldNumber_Vendor = 3,
  ORTBRequest_Item_Metric_FieldNumber_ExtProtoArray = 4,
  ORTBRequest_Item_Metric_FieldNumber_Ext = 5,
};

/**
 * This object is associated with an item as an array of metrics.
 * These metrics can offer insight to assist with decisioning such
 * as average recent viewability, click-through rate, etc.
 * Each metric is identified by its type, reports the value of the metric,
 * and optionally identifies the source or vendor measuring the value.
 **/
GPB_FINAL @interface ORTBRequest_Item_Metric : GPBMessage

/**
 * Type of metric being presented using exchange curated string names.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *type;

/**
 * Number representing the value of the metric.
 * \@required
 **/
@property(nonatomic, readwrite) float value;

/**
 * Source of the value using exchange curated string names.
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *vendor;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBRequest_Item_Deal

typedef GPB_ENUM(ORTBRequest_Item_Deal_FieldNumber) {
  ORTBRequest_Item_Deal_FieldNumber_Id_p = 1,
  ORTBRequest_Item_Deal_FieldNumber_Flr = 2,
  ORTBRequest_Item_Deal_FieldNumber_Flrcur = 3,
  ORTBRequest_Item_Deal_FieldNumber_At = 4,
  ORTBRequest_Item_Deal_FieldNumber_WseatArray = 5,
  ORTBRequest_Item_Deal_FieldNumber_WadomainArray = 6,
  ORTBRequest_Item_Deal_FieldNumber_ExtProtoArray = 7,
  ORTBRequest_Item_Deal_FieldNumber_Ext = 8,
};

/**
 * This object constitutes a specific deal that was struck a priori
 * between a seller and a buyer. Its presence indicates that this item
 * is available under the terms of that deal.
 **/
GPB_FINAL @interface ORTBRequest_Item_Deal : GPBMessage

/**
 * A unique identifier for the deal.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** Minimum deal price for this item expressed in CPM. */
@property(nonatomic, readwrite) double flr;

/**
 * Currency of the “flr” attribute specified using ISO-4217 alpha codes.
 * \@default "USD"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *flrcur;

/** Optional override of the overall auction type of the request. */
@property(nonatomic, readwrite) uint32_t at;

/** Whitelist of buyer seats allowed to bid on this deal. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *wseatArray;
/** The number of items in @c wseatArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wseatArray_Count;

/** Array of advertiser domains allowed to bid on this deal. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *wadomainArray;
/** The number of items in @c wadomainArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wadomainArray_Count;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBResponse

typedef GPB_ENUM(ORTBResponse_FieldNumber) {
  ORTBResponse_FieldNumber_Id_p = 1,
  ORTBResponse_FieldNumber_Bidid = 2,
  ORTBResponse_FieldNumber_Nbr = 3,
  ORTBResponse_FieldNumber_Cur = 4,
  ORTBResponse_FieldNumber_Cdata = 5,
  ORTBResponse_FieldNumber_SeatbidArray = 6,
  ORTBResponse_FieldNumber_ExtProtoArray = 7,
  ORTBResponse_FieldNumber_Ext = 8,
};

/**
 * This object is the bid response object under the Openrtb root.
 * Its id attribute is a reflection of the bid request ID.
 * The bidid attribute is an optional response tracking ID for bidders.
 * If specified, it will be available for use in substitution macros
 * placed in markup and notification URLs.
 * At least one Seatbid object is required, which contains
 * at least one Bid for an item.
 **/
GPB_FINAL @interface ORTBResponse : GPBMessage

/**
 * ID of the bid request to which this is a response;
 * must match the "request.id" attribute.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** Bidder generated response ID to assist with logging/tracking. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bidid;

/** Reason for not bidding if applicable. */
@property(nonatomic, readwrite) ORTBNoBidReason nbr;

/**
 * Bid currency using ISO-4217 alpha codes.
 * \@default "USD"
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *cur;

/**
 * Allows bidder to set data in the exchange’s cookie,
 * which can be retrieved on bid requests
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *cdata;

/** Array of “Seatbid” objects; 1+ required if a bid is to be made. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBResponse_Seatbid*> *seatbidArray;
/** The number of items in @c seatbidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger seatbidArray_Count;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

/**
 * Fetches the raw value of a @c ORTBResponse's @c nbr property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ORTBResponse_Nbr_RawValue(ORTBResponse *message);
/**
 * Sets the raw value of an @c ORTBResponse's @c nbr property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetORTBResponse_Nbr_RawValue(ORTBResponse *message, int32_t value);

#pragma mark - ORTBResponse_Seatbid

typedef GPB_ENUM(ORTBResponse_Seatbid_FieldNumber) {
  ORTBResponse_Seatbid_FieldNumber_Seat = 1,
  ORTBResponse_Seatbid_FieldNumber_Package = 2,
  ORTBResponse_Seatbid_FieldNumber_BidArray = 3,
  ORTBResponse_Seatbid_FieldNumber_ExtProtoArray = 4,
  ORTBResponse_Seatbid_FieldNumber_Ext = 5,
};

/**
 * A bid response can contain multiple Seatbid objects,
 * each on behalf of a different buyer seat and each
 * containing one or more individual bids. If multiple
 * items are presented in the request offer,
 * the package attribute can be used to specify if a seat
 * is willing to accept any impressions that it can win (default)
 * or if it is interested in winning any only if it can win them all as a group.
 **/
GPB_FINAL @interface ORTBResponse_Seatbid : GPBMessage

/** ID of the buyer seat on whose behalf this bid is made. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *seat;

/**
 * For offers with multiple items, this flag Indicates
 * if the bidder is willing to accept wins on a subset
 * of bids or requires the full group as a package.
 * \@default false
 **/
@property(nonatomic, readwrite) BOOL package;

/**
 * Array of 1+ "Bid" objects each related to an item.
 * Multiple bids can relate to the same item.
 **/
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBResponse_Seatbid_Bid*> *bidArray;
/** The number of items in @c bidArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger bidArray_Count;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBResponse_Seatbid_Bid

typedef GPB_ENUM(ORTBResponse_Seatbid_Bid_FieldNumber) {
  ORTBResponse_Seatbid_Bid_FieldNumber_Id_p = 1,
  ORTBResponse_Seatbid_Bid_FieldNumber_Item = 2,
  ORTBResponse_Seatbid_Bid_FieldNumber_Price = 3,
  ORTBResponse_Seatbid_Bid_FieldNumber_Deal = 4,
  ORTBResponse_Seatbid_Bid_FieldNumber_Cid = 5,
  ORTBResponse_Seatbid_Bid_FieldNumber_Tactic = 6,
  ORTBResponse_Seatbid_Bid_FieldNumber_Purl = 7,
  ORTBResponse_Seatbid_Bid_FieldNumber_Burl = 8,
  ORTBResponse_Seatbid_Bid_FieldNumber_Lurl = 9,
  ORTBResponse_Seatbid_Bid_FieldNumber_Exp = 10,
  ORTBResponse_Seatbid_Bid_FieldNumber_Mid = 11,
  ORTBResponse_Seatbid_Bid_FieldNumber_MacroArray = 12,
  ORTBResponse_Seatbid_Bid_FieldNumber_Media = 13,
  ORTBResponse_Seatbid_Bid_FieldNumber_ExtProtoArray = 14,
  ORTBResponse_Seatbid_Bid_FieldNumber_Ext = 15,
};

/**
 * A Seatbid object contains one or more Bid objects,
 * each of which relates to a specific item in the bid request
 * offer via the “item” attribute and constitutes an offer to buy
 * that item for a given price.
 **/
GPB_FINAL @interface ORTBResponse_Seatbid_Bid : GPBMessage

/**
 * Bidder generated bid ID to assist with logging/tracking.
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/**
 * ID of the item object in the related bid request; specifically "item.id".
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *item;

/**
 * Bid price expressed as CPM although the actual transaction is for a unit item only.
 * \@required
 **/
@property(nonatomic, readwrite) double price;

/**
 * Reference to a deal from the bid request if this bid pertains to a private marketplace deal;
 * specifically “deal.id”.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *deal;

/** Campaign ID or other similar grouping of brand-related ads. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

/**
 * Tactic ID to enable buyers to label bids for reporting to the
 * exchange the tactic through which their bid was submitted.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *tactic;

/** Pending notice URL called by the exchange when a bid has been declared the winner. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *purl;

/**
 * Billing notice URL called by the exchange when a winning bid becomes billable.
 * \@recommended
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *burl;

/** Loss notice URL called by the exchange when a bid is known to have been lost. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *lurl;

/**
 * Advisory as to the number of seconds the buyer is willing to wait
 * between auction and fulfilment.
 **/
@property(nonatomic, readwrite) uint32_t exp;

/**
 * ID to enable media to be specified by reference if previously uploaded
 * to the exchange rather than including it by value in the domain objects.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *mid;

/** Array of “Macro” objects that enable bid specific values to be substituted into markup; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ORTBResponse_Seatbid_Bid_Macro*> *macroArray;
/** The number of items in @c macroArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger macroArray_Count;

/**
 * Layer-4 domain object structure that specifies the media to be presented
 * if the bid is won conforming to the specification and version referenced
 * in “openrtb.domainspec” and “openrtb.domainver”.
 * For AdCOM v1.x, the objects allowed here are “Ad” and any objects subordinate
 * thereto as specified by AdCOM.
 **/
@property(nonatomic, readwrite, strong, null_resettable) GPBAny *media;
/** Test to see if @c media has been set. */
@property(nonatomic, readwrite) BOOL hasMedia;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

#pragma mark - ORTBResponse_Seatbid_Bid_Macro

typedef GPB_ENUM(ORTBResponse_Seatbid_Bid_Macro_FieldNumber) {
  ORTBResponse_Seatbid_Bid_Macro_FieldNumber_Key = 1,
  ORTBResponse_Seatbid_Bid_Macro_FieldNumber_Value = 2,
  ORTBResponse_Seatbid_Bid_Macro_FieldNumber_ExtProtoArray = 3,
  ORTBResponse_Seatbid_Bid_Macro_FieldNumber_Ext = 4,
};

/**
 * This object constitutes a buyer defined key/value pair used to inject
 * dynamic values into media markup. While they apply to any media markup
 * irrespective of how it is conveyed, the principle use case is for media
 * that was uploaded to the exchange prior to the transaction
 * (e.g., pre-registered for creative quality review) and referenced in bid.
 **/
GPB_FINAL @interface ORTBResponse_Seatbid_Bid_Macro : GPBMessage

/**
 * Name of a buyer specific macro.
 * \@required
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

/** Value to substitute for each instance of the macro found in markup. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

/** Optional vendor-specific extensions. */
@property(nonatomic, readwrite, strong, null_resettable) GPBStruct *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

/** Legacy proto extensions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GPBAny*> *extProtoArray;
/** The number of items in @c extProtoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extProtoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
