#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef STACKPRODUCTPRESENTATION_SWIFT_H
#define STACKPRODUCTPRESENTATION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="StackProductPresentation",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@protocol STKPrivacySheetPresenterDelegate;
@class NSString;
@class UIViewController;

SWIFT_CLASS_NAMED("PrivacySheetPresenter")
@interface STKPrivacySheetPresenter : NSObject
@property (nonatomic, weak) id <STKPrivacySheetPresenterDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)setWithJson:(NSDictionary<NSString *, id> * _Nonnull)json;
- (void)prepareFor:(UIViewController * _Nullable)rootViewController;
- (void)show;
- (void)hide;
@end



SWIFT_PROTOCOL_NAMED("PrivacySheetPresenterDelegate")
@protocol STKPrivacySheetPresenterDelegate
- (void)privacySheetDidFailToPresentModal:(STKPrivacySheetPresenter * _Nonnull)privacySheet error:(NSError * _Nonnull)error;
- (void)privacySheetWillPresentModal:(STKPrivacySheetPresenter * _Nonnull)privacySheet;
- (void)privacySheetDidDismissModal:(STKPrivacySheetPresenter * _Nonnull)privacySheet;
- (void)privacySheetWillLeaveApplication:(STKPrivacySheetPresenter * _Nonnull)privacySheet;
- (void)privacySheetDidFailToLeaveApplication:(STKPrivacySheetPresenter * _Nonnull)privacySheet error:(NSError * _Nonnull)error;
@end

@class UIView;
@class NSURL;
@protocol STKProductNavigationDelegate;
enum STKProductOverlayStyle : NSUInteger;
@protocol STKProductOverlayDelegate;

SWIFT_CLASS_NAMED("Product")
@interface STKProduct : NSObject
- (void)prepareWithParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)beginViewOn:(UIView * _Nonnull)view controller:(UIViewController * _Nonnull)controller completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)endViewWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)navigateTo:(NSURL * _Nullable)destination resolveLinkAlways:(BOOL)resolveLinkAlways delegate:(id <STKProductNavigationDelegate> _Nullable)delegate;
- (void)presentOverlayWithStyle:(enum STKProductOverlayStyle)style from:(UIViewController * _Nullable)rootViewController delegate:(id <STKProductOverlayDelegate> _Nullable)delegate;
- (void)hideOverlay;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class STKProductNavigation;

SWIFT_PROTOCOL_NAMED("ProductNavigationDelegate")
@protocol STKProductNavigationDelegate
- (void)productNavigationDidFailToNavigate:(STKProductNavigation * _Nonnull)productNavigation error:(NSError * _Nonnull)error;
- (void)productNavigationWillPresentModal:(STKProductNavigation * _Nonnull)productNavigation;
- (void)productNavigationDidDismissModal:(STKProductNavigation * _Nonnull)productNavigation;
- (void)productNavigationWillLeaveApplication:(STKProductNavigation * _Nonnull)productNavigation :(NSString * _Nullable)url;
@end


@interface STKProduct (SWIFT_EXTENSION(StackProductPresentation)) <STKProductNavigationDelegate>
- (void)productNavigationDidFailToNavigate:(STKProductNavigation * _Nonnull)productNavigation error:(NSError * _Nonnull)error;
- (void)productNavigationWillPresentModal:(STKProductNavigation * _Nonnull)productNavigation;
- (void)productNavigationDidDismissModal:(STKProductNavigation * _Nonnull)productNavigation;
- (void)productNavigationWillLeaveApplication:(STKProductNavigation * _Nonnull)productNavigation :(NSString * _Nullable)url;
@end

@class STKProductOverlay;

SWIFT_PROTOCOL_NAMED("ProductOverlayDelegate")
@protocol STKProductOverlayDelegate
- (void)overlayDidFailToLoad:(STKProductOverlay * _Nullable)overlay error:(NSError * _Nonnull)error;
- (void)overlayDidReceiveUserTap:(STKProductOverlay * _Nonnull)overlay;
- (void)overlayWillStartPresentation:(STKProductOverlay * _Nonnull)overlay;
- (void)overlayDidFinishDismissal:(STKProductOverlay * _Nonnull)overlay;
@end


@interface STKProduct (SWIFT_EXTENSION(StackProductPresentation)) <STKProductOverlayDelegate>
- (void)overlayDidFailToLoad:(STKProductOverlay * _Nullable)overlay error:(NSError * _Nonnull)error;
- (void)overlayDidReceiveUserTap:(STKProductOverlay * _Nonnull)overlay;
- (void)overlayWillStartPresentation:(STKProductOverlay * _Nonnull)overlay;
- (void)overlayDidFinishDismissal:(STKProductOverlay * _Nonnull)overlay;
@end



SWIFT_CLASS_NAMED("ProductImpression")
@interface STKProductImpression : NSObject
- (nullable instancetype)initWithParameters:(NSDictionary<NSString *, id> * _Nonnull)parameters error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (void)prepareWithCompletion:(void (^ _Nonnull)(NSError * _Nullable))completion;
- (void)beginViewOn:(UIView * _Nonnull)view controller:(UIViewController * _Nonnull)controller completion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)endViewWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@interface STKProductImpression (SWIFT_EXTENSION(StackProductPresentation))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull itemIdentifierKey;)
+ (NSString * _Nonnull)itemIdentifierKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkAttributionSignatureKey;)
+ (NSString * _Nonnull)adNetworkAttributionSignatureKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkCampaignIdentifierKey;)
+ (NSString * _Nonnull)adNetworkCampaignIdentifierKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkSourceIdentifierKey;)
+ (NSString * _Nonnull)adNetworkSourceIdentifierKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkIdentifierKey;)
+ (NSString * _Nonnull)adNetworkIdentifierKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkNonceKey;)
+ (NSString * _Nonnull)adNetworkNonceKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkTimestampKey;)
+ (NSString * _Nonnull)adNetworkTimestampKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkSourceAppStoreIdentifierKey;)
+ (NSString * _Nonnull)adNetworkSourceAppStoreIdentifierKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkVersionKey;)
+ (NSString * _Nonnull)adNetworkVersionKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkFidelitiesKey;)
+ (NSString * _Nonnull)adNetworkFidelitiesKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adNetworkFidelityKey;)
+ (NSString * _Nonnull)adNetworkFidelityKey SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull adAttributionCompactJWS;)
+ (NSString * _Nonnull)adAttributionCompactJWS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSArray<NSString *> * _Nonnull supportedSKAdNetworkVersions;)
+ (NSArray<NSString *> * _Nonnull)supportedSKAdNetworkVersions SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("ProductNavigation")
@interface STKProductNavigation : NSObject
@property (nonatomic, weak) id <STKProductNavigationDelegate> _Nullable delegate;
- (nonnull instancetype)initWithImpression:(STKProductImpression * _Nullable)impression OBJC_DESIGNATED_INITIALIZER;
- (void)navigateTo:(NSURL * _Nullable)destination;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




SWIFT_CLASS_NAMED("ProductOverlay")
@interface STKProductOverlay : NSObject
@property (nonatomic, weak) id <STKProductOverlayDelegate> _Nullable delegate;
- (nullable instancetype)initWithImpression:(STKProductImpression * _Nonnull)impression style:(enum STKProductOverlayStyle)style error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (void)presentFrom:(UIViewController * _Nullable)rootViewController;
- (void)hide;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM_NAMED(NSUInteger, STKProductOverlayStyle, "Style", open) {
  STKProductOverlayStyleDefault = 0,
  STKProductOverlayStyleCustom = 1,
};





#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
